
server:
  port: 8083
  
 # for Eureka servier config 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service          #http://localhost:8081 #lb://book-service
          predicates:
            - Path=/book/**
        - id: subscription-service
          uri: lb://subscription-service  #http://localhost:8082 #lb://subscription-service
          predicates:
            - Path=/subscriptionService/**
